app: tensorquick
save_dir: ~/Pictures/TensorQuick
models:
- code_name: flux-1-dev
  description: FLUX.1 [dev] is a 12 billion parameter rectified flow transformer capable
    of generating images from text descriptions.
  name: FLUX.1-dev
  gpu_type: H100
  preview: image://tensorquick/flux.1-dev.png
- code_name: flux-1-schnell
  description: FLUX.1 [schnell] is a 12 billion parameter rectified flow transformer capable
    of generating images from text descriptions.
  name: FLUX.1-schnell
  gpu_type: H100
  preview: image://tensorquick/flux.1-schnell.png
- code_name: stable-diffusion-xl
  description: This is a model that can be used to generate and modify images based
    on text prompts. It is a Latent Diffusion Model that uses two fixed, pretrained
    text encoders (OpenCLIP-ViT/G and CLIP-ViT/L).
  name: Stable Diffusion XL
  gpu_type: A10G
  preview: image://tensorquick/stable-diffusion-xl.png
- code_name: mochi-1
  name: Mochi 1
  description: DESC
  gpu_type: H100
  preview: image://tensorquick/mochi-1.png
- code_name: juggernaut-xl-v9
  name: Juggernaut XL v9
  description: DESC
  gpu_type: H100
  preview: image://tensorquick/juggernaut-xl.png
- code_name: realvisxl-v6
  name: Realistic Vision V6
  description: DESC
  gpu_type: H100
  preview: image://tensorquick/realistic-xl.png
- code_name: dreamshaper-xl
  name: DreamShaper XL
  description: DESC
  gpu_type: H100
  preview: image://tensorquick/dreamshaper-xl.png