name: Publish to Test PyPI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - master

jobs:
  build-n-publish-test:
    name: Build and publish to Test PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools

    - name: Build package
      run: |
        python -m build --sdist --wheel

    - name: Verify package
      run: twine check dist/*

    - name: Publish to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        twine upload --repository testpypi dist/* --skip-existing